# Cấu hình Netlify để hỗ trợ URL rewriting

[[redirects]]
  from = "/san-pham/*"
  to = "/pages/san-pham/:splat.html"
  status = 200

[[redirects]]
  from = "/lieu-trinh/*"
  to = "/pages/lieu-trinh/:splat.html"
  status = 200

[[redirects]]
  from = "/thu-vien-kien-thuc/*"
  to = "/pages/thu-vien-kien-thuc/:splat.html"
  status = 200

[[redirects]]
  from = "/gioi-thieu"
  to = "/pages/gioi-thieu.html"
  status = 200

[[redirects]]
  from = "/lien-he"
  to = "/pages/lien-he.html"
  status = 200

[[redirects]]
  from = "/tu-van"
  to = "/pages/tu-van.html"
  status = 200

# Cấu hình 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
